version: '3.8'
services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ibuildz
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=changeme
      - S3_BUCKET_NAME=changeme
      - AWS_ACCESS_KEY_ID=changeme
      - AWS_SECRET_ACCESS_KEY=changeme
      - AWS_REGION=ap-south-1
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ibuildz
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data: 
